spring.application.name=ProductProject
spring.data.mongodb.uri=mongodb://localhost:27017/ProductData

spring.security.user.name=admin
spring.security.user.password=admin123

management.endpoints.web.exposure.include=info,health
management.endpoints.web.exposure.exclude=loggers,env,beans
#management.endpoints.web.base-path=/details
management.endpoints.web.exposure.include=*
